#!/bin/bash
if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

JENKINS_PUBLIC_SSH_KEY_PATH="${JENKINS_PUBLIC_SSH_KEY_PATH:-/home/jenkins/.ssh/id_rsa.pub}"

if [ ! -f "${JENKINS_PUBLIC_SSH_KEY_PATH}" ]; then
    die "Can not find the public key for the jenkins user."
fi

cp "${JENKINS_PUBLIC_SSH_KEY_PATH}" "${TMP_HOOKS_PATH}/jenkins-public-ssh-key"
